
ifndef ROOT
$(error ROOT is not set, use one of the example makefiles and set the ROOT path)
endif

# Set SDK path and include its makefile
SDK_ROOT = $(ROOT)/sdk
include $(SDK_ROOT)/Makefile

.PHONY: all
all:
	@echo "Root makefile does not build anything."
